/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.43 from the
 * contents of ObjDemo.xs. Do not edit this file, edit ObjDemo.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "ObjDemo.xs"
#include <string>

/* A compact C++ fixture pinning the SDK v2 surface: a T_PTROBJ-style native
 * object (host pointer crossing as a registry id inside a blessed IV ref),
 * plus AV/HV construction, hash stores/fetches, and sv_bless. */

class Counter {
public:
    Counter(const char *label) : label_(label), n_(0) {}
    long long incr(long long by) { n_ += by; return n_; }
    const std::string &label() const { return label_; }
    long long n() const { return n_; }

private:
    std::string label_;
    long long n_;
};

#ifdef __cplusplus
extern "C" {
#endif
#define PERL_NO_GET_CONTEXT
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#ifdef __cplusplus
};
#endif

typedef Counter * Obj_Demo;

#line 42 "ObjDemo.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%" UVxf ")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

#line 186 "ObjDemo.c"

XS_EUPXS(XS_Obj__Demo__new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Obj__Demo__new)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "classname, label");
    {
	char *	classname = (char *)SvPV_nolen(ST(0))
;
	const char *	label = (const char *)SvPV_nolen(ST(1))
;
	Obj_Demo	RETVAL;
#line 40 "ObjDemo.xs"
{
	RETVAL = new Counter(label);
}
#line 204 "ObjDemo.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
		    sv_setref_pv(RETVALSV, "Obj::Demo",
		    (void*)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Obj__Demo_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Obj__Demo_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	Obj_Demo	self;

                if (sv_derived_from(ST(0), "Obj::Demo")) {
                        IV tmp = SvIV((SV*)SvRV(ST(0)));
                        self = INT2PTR(Obj_Demo, tmp);
                }
                else
                        croak("self is not of type Obj::Demo")
;
#line 50 "ObjDemo.xs"
{
	delete self;
}
#line 237 "ObjDemo.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Obj__Demo_incr); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Obj__Demo_incr)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, by");
    {
	Obj_Demo	self;
	IV	by = (IV)SvIV(ST(1))
;
	IV	RETVAL;
	dXSTARG;

                if (sv_derived_from(ST(0), "Obj::Demo")) {
                        IV tmp = SvIV((SV*)SvRV(ST(0)));
                        self = INT2PTR(Obj_Demo, tmp);
                }
                else
                        croak("self is not of type Obj::Demo")
;
#line 59 "ObjDemo.xs"
{
	RETVAL = self->incr(by);
}
#line 267 "ObjDemo.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Obj__Demo_stats); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Obj__Demo_stats)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	Obj_Demo	self;
	SV *	RETVAL;

                if (sv_derived_from(ST(0), "Obj::Demo")) {
                        IV tmp = SvIV((SV*)SvRV(ST(0)));
                        self = INT2PTR(Obj_Demo, tmp);
                }
                else
                        croak("self is not of type Obj::Demo")
;
#line 69 "ObjDemo.xs"
{
	HV *hash = newHV();
	(void)hv_stores(hash, "label", newSVpv(self->label().c_str(), self->label().size()));
	(void)hv_stores(hash, "count", newSVuv((UV)self->n()));
	HV *stash = gv_stashpv("Obj::Demo::Stats", 1);
	RETVAL = SvREFCNT_inc(sv_bless(sv_2mortal(newRV_inc((SV*)hash)), stash));
}
#line 299 "ObjDemo.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Obj__Demo); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Obj__Demo)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if PERL_VERSION_LE(5, 8, 999) /* PERL_VERSION_LT is 5.33+ */
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("Obj::Demo::_new", XS_Obj__Demo__new);
        newXS_deffile("Obj::Demo::DESTROY", XS_Obj__Demo_DESTROY);
        newXS_deffile("Obj::Demo::incr", XS_Obj__Demo_incr);
        newXS_deffile("Obj::Demo::stats", XS_Obj__Demo_stats);
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

